FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Indobotanical

First version of Indobotanical

## Transaction [/transactions]

### Create Transactions [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "data": {
                "products": [
                    {
                        "productId": "5d846472e41e614e3bffdef2",
                        "amount": 1
                    },
                    {
                        "productId": "5d8470ede41e6151d13734b1",
                        "amount": 1
                    }
                ],
                "promoCode": "Kratom01"
            }
        }

+ Response 201 (application/json)

    + Body

            {
                "id": "5d866ca17ec12c4eb217ace1",
                "products": [
                    {
                        "id": "5d846472e41e614e3bffdef2",
                        "name": "Kratom 2",
                        "description": "Lorem ipsum dolor si kratom",
                        "stock": 20,
                        "price": 35,
                        "thumbnail": "image.png",
                        "avaibility": true,
                        "createdAt": "2019-09-20T12:32:34.232+07:00",
                        "updatedAt": "0001-01-01T00:00:00Z"
                    },
                    {
                        "id": "5d8470ede41e6151d13734b1",
                        "name": "Kratom 2",
                        "description": "Lorem ipsum dolor si kratom",
                        "stock": 20,
                        "price": 35,
                        "thumbnail": "image.png",
                        "avaibility": true,
                        "createdAt": "2019-09-20T13:25:49.897+07:00",
                        "updatedAt": "0001-01-01T00:00:00Z"
                    }
                ],
                "userId": "5d8465ed941ab90004518664",
                "totalPrice": 63,
                "status": 0,
                "paymentProof": null,
                "createdAt": "2019-09-22T01:32:01.073356+07:00",
                "updatedAt": "0001-01-01T00:00:00Z"
            }