FORMAT: 1A
HOST: https://indobotanical.herokuapp.com

# Indobotanical

First version of Indobotanical

## Auth [/auth]

### Login [POST /login]

+ Request (application/json)

        {
            "data": {
                "email": "email",
                "password": "password",
            }
        }
        
+ Response 201 (application/json)

        {
            "message": "Login success",
            "token": "bla bla bla",
        }
        
### Register [POST /register]

+ Request (application/json)

        {
            "data": {
                "name": "Badrus",
                "email": "hi@gmail.com",
                "password": "secret",
                "address": "Buah Batu Bandung",
                "city": "Bandung",
                "country": "Indonesia",
            }
        }
        
+ Response 201 (application/json)

        {
            "message": "User Created",
        }
        
+ Response 409 (application/json)

        {
            "statusCode" 409,
            "message": "Your email are already registered before",
        }

## Products [/products]

### List[GET]

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "message": null,
            "data": [
                {
                    "id": "5d748de07ec12c0d7030ad21",
                    "name": "Kratom 1",
                    "description": "Lorem ipsum dolor si kratom",
                    "stock": 20,
                    "price": 35,
                    "thumbnail": "image.png",
                    "avaibility": true,
                    "createdAt": "2019-09-08T12:13:04.765+07:00",
                    "updatedAt": "0001-01-01T00:00:00Z"
                },
                {
                    "id": "5d845f02e41e61459bfd7c81",
                    "name": "Kratom 2",
                    "description": "Lorem ipsum dolor si kratom",
                    "stock": 20,
                    "price": 35,
                    "thumbnail": "image.png",
                    "avaibility": true,
                    "createdAt": "2019-09-08T12:13:04.765+07:00",
                    "updatedAt": "0001-01-01T00:00:00Z"
                }
            ]
        }

### Show[GET /:id]

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "message": null,
            "data": {
                "id": "5d748de07ec12c0d7030ad21",
                "name": "Kratom 2",
                "description": "Lorem ipsum dolor si kratom",
                "stock": 20,
                "price": 35,
                "thumbnail": "image.png",
                "avaibility": true,
                "createdAt": "2019-09-08T12:13:04.765+07:00",
                "updatedAt": "0001-01-01T00:00:00Z"
            }
        }

## Transaction [/transactions]

### List [GET]

+ Response 201 (application/json)

        {
            "statusCode": 200,
            "message": null,
            "data": [
                {
                    "id": "5d867487461770000429942f",
                    "products": [
                        {
                            "id": "5d84657e941ab90004518662",
                            "name": "Kratom 2",
                            "description": "Lorem ipsum dolor si kratom",
                            "stock": 20,
                            "price": 35,
                            "thumbnail": "image.png",
                            "avaibility": true,
                            "createdAt": "2019-09-20T05:37:02.184Z",
                            "updatedAt": "0001-01-01T00:00:00Z"
                        },
                        {
                            "id": "5d8465a1941ab90004518663",
                            "name": "Kratom 2",
                            "description": "Lorem ipsum dolor si kratom",
                            "stock": 20,
                            "price": 35,
                            "thumbnail": "image.png",
                            "avaibility": true,
                            "createdAt": "2019-09-20T05:37:37.877Z",
                            "updatedAt": "0001-01-01T00:00:00Z"
                        }
                    ],
                    "userId": "5d8465ed941ab90004518664",
                    "totalPrice": 63,
                    "status": 0,
                    "paymentProof": null,
                    "createdAt": "2019-09-21T19:05:43.216Z",
                    "updatedAt": "0001-01-01T00:00:00Z"
                }
                {
                    "id": "9d867487461770000429942f",
                    "products": [
                        {
                            "id": "5d84657e941ab90004518662",
                            "name": "Kratom 2",
                            "description": "Lorem ipsum dolor si kratom",
                            "stock": 20,
                            "price": 35,
                            "thumbnail": "image.png",
                            "avaibility": true,
                            "createdAt": "2019-09-20T05:37:02.184Z",
                            "updatedAt": "0001-01-01T00:00:00Z"
                        },
                        {
                            "id": "5d8465a1941ab90004518663",
                            "name": "Kratom 2",
                            "description": "Lorem ipsum dolor si kratom",
                            "stock": 20,
                            "price": 35,
                            "thumbnail": "image.png",
                            "avaibility": true,
                            "createdAt": "2019-09-20T05:37:37.877Z",
                            "updatedAt": "0001-01-01T00:00:00Z"
                        }
                    ],
                    "userId": "5d8465ed941ab90004518664",
                    "totalPrice": 63,
                    "status": 0,
                    "paymentProof": null,
                    "createdAt": "2019-09-21T19:05:43.216Z",
                    "updatedAt": "0001-01-01T00:00:00Z"
                }
            ]
        }

### Create Transactions [POST]

+ Request (application/json)

        {
            "data": {
                "products": [
                    {
                        "productId": "5d846472e41e614e3bffdef2",
                        "amount": 1
                    },
                    {
                        "productId": "5d8470ede41e6151d13734b1",
                        "amount": 1
                    }
                ],
                "promoCode": "Kratom01"
            }
        }

+ Response 201 (application/json)

    + Body

            {
                "id": "5d866ca17ec12c4eb217ace1",
                "products": [
                    {
                        "id": "5d846472e41e614e3bffdef2",
                        "name": "Kratom 2",
                        "description": "Lorem ipsum dolor si kratom",
                        "stock": 20,
                        "price": 35,
                        "thumbnail": "image.png",
                        "avaibility": true,
                        "createdAt": "2019-09-20T12:32:34.232+07:00",
                        "updatedAt": "0001-01-01T00:00:00Z"
                    },
                    {
                        "id": "5d8470ede41e6151d13734b1",
                        "name": "Kratom 2",
                        "description": "Lorem ipsum dolor si kratom",
                        "stock": 20,
                        "price": 35,
                        "thumbnail": "image.png",
                        "avaibility": true,
                        "createdAt": "2019-09-20T13:25:49.897+07:00",
                        "updatedAt": "0001-01-01T00:00:00Z"
                    }
                ],
                "userId": "5d8465ed941ab90004518664",
                "totalPrice": 63,
                "status": 0,
                "paymentProof": null,
                "createdAt": "2019-09-22T01:32:01.073356+07:00",
                "updatedAt": "0001-01-01T00:00:00Z"
            }